version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: omniroute_server_1
      APP_PORT: 20128
      PROXY_AUTH_ADD: "false"

  server:
    image: diegosouzapw/omniroute:latest
    container_name: omniroute_server_1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "20128:20128"
    environment:
      - PORT=20128
      - NODE_ENV=production
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
